spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goopper?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.6a814d5cbc56f413
            client-secret: b075bbd36668fdf127e69e2a1aae02e5ec2019ac
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
s3:
  endpoint: https://s3.tebi.io
  region: de
  access-key: uNSPywZt8jog4dbA
  secret-key: wRn2JCbVu0EWvj6g7QBLRqS3P7dr1TDd75fwN9Qo
  bucket: goopper
cors:
  allowed-origins: http://localhost:3000,https://app.goopper.top
security:
  white-list: /login,/oauth/*/url,/oauth/*/auth,/oauth/login/*,/health
error-log: true